meta_product_name: "Moving Out Sale"
meta_title: "Moving Out Sale - Pakki & Sam"
meta_description: "All the items of our Moving Out Sale! Contact us via FB for more informations"
meta_image: "cover.png" # should exist in `app/assets/images/`
